# Generated by Django 5.2.12 on 2026-03-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('soft', 'Soft Drinks'), ('coffee', 'Coffee'), ('beer', 'Beer'), ('cocktail', 'Cocktail'), ('water', 'Water'), ('other', 'Other')], default='other', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
