# Generated by Django 5.2.12 on 2026-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_on_live_controls',
            field=models.BooleanField(default=True),
        ),
    ]
